<!DOCTYPE html>
<html lang="en" dir="ltr"><head>
  
                           
     


<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="generator" content="Hugo 0.87.0" />
<title>Hydrology Distributions: Part I | hydroblog</title>


<meta property="twitter:site" content="@joshualerickson">
<meta property="twitter:creator" content="@joshualerickson">







  
    
  
<meta name="description" content="Part I in a series about hydrology distributions. Part I goes over descriptive statistics and pmf, pdf and cdf.">


<meta property="og:site_name" content="hydroblog">
<meta property="og:title" content="Hydrology Distributions: Part I | hydroblog">
<meta property="og:description" content="Part I in a series about hydrology distributions. Part I goes over descriptive statistics and pmf, pdf and cdf." />
<meta property="og:type" content="page" />
<meta property="og:url" content="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/" />
<meta property="og:locale" content="en">




    
        <meta property="og:image" content="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/features.png" >
        <meta property="twitter:card" content="summary_large_image">
        <meta name="twitter:image" content="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/features.png" >
    
    
  <meta itemprop="name" content="Hydrology Distributions: Part I">
<meta itemprop="description" content="Part I in a series about hydrology distributions. Part I goes over descriptive statistics and pmf, pdf and cdf."><meta itemprop="datePublished" content="2021-06-07T00:00:00+00:00" />
<meta itemprop="dateModified" content="2021-06-07T00:00:00+00:00" />
<meta itemprop="wordCount" content="2961"><meta itemprop="image" content="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/features.png">
<meta itemprop="keywords" content="R,Hydrology," />
  
  <!--[if IE]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <link rel="shortcut icon" href="/img/water.ico" type="image/x-icon">
  <link rel="icon" href="/img/water.ico" type="image/x-icon">
  
  
  <link rel="stylesheet" href="/style.main.min.5477c20f89738a32763391bbc2f43dbdfc2db0e7faba550c86cac92c99efa6b6.css" integrity="sha256-VHfCD4lzijJ2M5G7wvQ9vfwtsOf6ulUMhsrJLJnvprY=" media="screen">
  
  
  <script src="/panelset.min.078a92db9bd3228df502db3d9e0453c3cf3d910abe3f8deca0ad196c7071ad41.js" type="text/javascript"></script>
  
  
  <script src="/main.min.0fe7313cc594fa307cdf603bcf065f456b2b2539a1f686ce5f3445d01e702a8d.js" type="text/javascript"></script>
</head>
<body>
      <div class="grid-container single-sidebar">
<header class="site-header pt4 pb2 mb4 bb b--transparent ph5 headroom z-max" role="banner">
  <nav class="site-nav db dt-l w-100" role="navigation">
    <a class="site-brand db dtc-l v-mid link no-underline w-100 w-33-l tc tl-l" href="https://hydroblog.netlify.com/" title="Home">
      <img src="/img/water_blue.png" class="dib db-l h2 w-auto" alt="hydroblog">
    </a>
    <div class="site-links db dtc-l v-mid w-100 w-47-l tc tr-l mt3 mt0-l ttu tracked">
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 " href="/about/" title="About hydroblog">About</a>
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 active" href="/blog/" title="Blog">Blog</a>
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 " href="/project/" title="Project Portfolio">Projects</a>
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 " href="/talk/" title="Talks">Talks</a>
      
      
    </div>
  </nav>
</header>

<main class="page-main pa4" role="main">
  <section class="page-content mw7 center">
    <article class="post-content pa0 pr3-l">
      <header class="post-header">
        <h1 class="f1 lh-solid measure-narrow mb3 fw4">Hydrology Distributions: Part I</h1>
        <h4 class="f4 mt0 mb4 lh-title measure">Part I in a series about hydrology distributions. Part I goes over descriptive statistics and pmf, pdf and cdf.</h4>
        <p class="f6 measure lh-copy mv1">By Josh Erickson in <a href="https://hydroblog.netlify.com/categories/r">R</a>  <a href="https://hydroblog.netlify.com/categories/hydrology">Hydrology</a> </p>
        <p class="f7 db mv0 ttu">June 7, 2021</p>
      </header>
      <section class="post-body pt5 pb4">
        
<script src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/header-attrs/header-attrs.js"></script>
  <link rel="stylesheet" href="style.css" type="text/css" />


<pre class="r"><code>library(wildlandhydRo)
library(evd)
library(fitdistrplus)
library(tidyverse)
library(patchwork)
library(latex2exp)
library(moments)
theme_set(theme_bw())</code></pre>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>This will be part one of a three part blog series <em>‘Hydrology Distributions’</em> where we’ll look at different distributions in R using a handful of packages. A lot of times in hydrology you’ll end up collecting data (rainfall, snowdepth, runoff, etc) to try and fit a theoretical distribution for further analysis, e.g. frequency, probabilities, hypothesis testing etc. These probability distributions come in all shapes and sizes (literally) and can be confusing at times but hopefully we can break these concepts down without too much incredulity from those pesky/pedantic statisticians 😊. First (part I), we’ll look at descriptive statistics and probability distributions (pmf and pdf). Second (part II), we’ll bring in some data and compare distributions visually for some commonly used theoretical distributions in hydrology, e.g. normal (N), lognormal (LN), log Pearson type III (LP3), Pearson (P), Gumbel (G), Weibull (W) and Generalized Extreme-value Distribution (GEV). Third (part III), we’ll use a few goodness-of-fit tests to see which theoretical distribution best represents the underlying empirical distribution.</p>
</div>
<div id="part-i" class="section level1">
<h1>Part I</h1>
<p>For part one we will get pretty ‘<em>mathy</em>’ by looking at descriptive stats and probability distributions and how they are derived. This is not meant to be a full blown course into statistics! Thus, I’m assuming the reader has some basic understanding of statistics and calculus but if you want more information please see this book from <span class="citation">@maity2018statistical</span> titled ‘<em>Statistical Methods in Hydrology and Hydroclimatology</em>’. This book does not have a free copy but is worth the buy if you can. Otherwise, here are some other sources that I think would be relevant to the series (<a href="https://tinyheero.github.io/2016/03/17/prob-distr.html">prob-distr</a>, <a href="https://rafalab.github.io/dsbook/distributions.html">distributions</a>).</p>
<p>So, what is a distribution? In a basic sense, a distribution is a set of observations (discrete or continuous) that shows how this set is distributed or how frequently values occur, e.g. <span class="math inline">\(banfield = \{1,4,5,5.3,3.546,10, \dots, n\}\)</span>. This set of observations (<span class="math inline">\(banfield\)</span>) can then be used graphically (plotting), descriptively (central tendency, dispersion, skewness and tailedness) or inferentially (theoretical distributions) to uncover more about the underlying data. So, let’s bring in some daily SWE data from a Snow Telemetry (SNOTEL) site (<span class="math inline">\(banfield\)</span>) and see what the data looks like graphically. We can do this by looking at a histogram (counting) or density plot. This gives us an idea of how the data is distributed and where values frequently occur.</p>
<div id="plotting" class="section level2">
<h2>Plotting</h2>
<pre class="r"><code>banfield &lt;- batch_SNOTELdv(sites = 311)
hist &lt;- ggplot(data = banfield, aes(snow_water_equivalent)) +
  geom_histogram() + labs(title = &#39;Histogram&#39;, x = &#39;Snow Water Equivalent (SWE) inches&#39;)

dens &lt;- ggplot(data = banfield, aes(snow_water_equivalent)) +
  geom_density() + labs(title = &#39;Density&#39;, x = &#39;Snow Water Equivalent (SWE) inches&#39;)

both &lt;- ggplot(data = banfield, aes(snow_water_equivalent, ..count..)) +  
  geom_histogram() +
  geom_density() +
  labs(x = &#39;Snow Water Equivalent (SWE) inches&#39;)

(hist | dens ) / both</code></pre>
<p><img src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/figure-html/unnamed-chunk-3-1.png" width="960" /></p>
<p>This is fine but as you can see most of the readings are zero (no snow!) so let’s just grab the month of April as this has some significance with runoff, i.e. high April SWE correlates with high runoff.</p>
<p><img src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/figure-html/unnamed-chunk-4-1.png" width="960" /></p>
<p>Ahhh, much better! As you can see, we start to get a better idea of how the data is distributed but this is just visual. Sometimes this is all you need but for other times that’s where descriptive statistics come in handy. Destriptive statistics will help us put a number to what we see!</p>
</div>
<div id="descriptive-stats" class="section level2">
<h2>Descriptive Stats</h2>
<p>Now we can look at some descriptive stats from these observations (<span class="math inline">\(banfield\)</span>). But first, let’s go over the common stats briefly, e.g. central tendency, dispersion, skewness and tailedness.</p>
<div id="central-tendency" class="section level3">
<h3>Central Tendency</h3>
<p>Central tendency describes where the data is most occurring, e.g. mean, median, mode. This helps us understand it’s ‘<strong>central tendency</strong>’ 😆, which can be useful for inferring population parameters (theretical distributions) or just getting a quick idea of the average. Below are the equations for calculating the mean, median and mode;</p>
<center>
<b>Mean</b>
</center>
<span class="math display">\[ \displaystyle \bar{x} = \frac{\sum_{i=1}^n x_{i}}{n}\]</span>
<center>
<b>Median</b>
</center>
<span class="math display">\[ \displaystyle \bar{x}_{md} = \frac{(n+1)}{2}\]</span>
<center>
<b>Mode</b>
</center>
<p><span class="math display">\[ \displaystyle \mu_{mo}=\arg \max\limits_{x_{i}}[p_{x}(x_{i})]\]</span></p>
<p>Sometimes this is all you need for your analysis; however, this can be misleading (most of time) without knowing other information like dispersion (variance).</p>
</div>
<div id="dispersion" class="section level3">
<h3>Dispersion</h3>
<p>Dispersion is the measure of spread from the central tendency. This is really helpful in that it let’s us know how clustered our data is or is not. For example, you can have the same mean but different dispersion as the figure below shows. This is a big difference, right? This is why providing the mean and standard deviation is so important when reporting data.</p>
<p><img src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/figure-html/unnamed-chunk-5-1.png" width="960" /></p>
<p>Below are the equations for calculating variance and standard deviation;</p>
<center>
<b>Variance</b>
</center>
<span class="math display">\[S^2=\frac{\sum_{i=1}^{n}(x_{i}-\bar{x})^2}{n-1} \]</span>
<center>
<b>Standard Deviation</b>
</center>
<p><span class="math display">\[S=\sqrt{\frac{\sum_{i=1}^{n}(x_{i}-\bar{x})^2}{n-1}} \]</span></p>
<p>As you can see, the standard deviation is just the square root of the variance. This is nice because it puts it <strong>back</strong> into the original scale of the data!</p>
</div>
<div id="skewness" class="section level3">
<h3>Skewness</h3>
<p>Skewness is the measure of symmetry. In other words, how does our data look on both sides of our central value (mean, median)? Is it symmetric? Is it longer on one side, etc? This is helpful because some data might be skewed right, left or barely at all and that can change how you infer meaning (we’ll go over this later).</p>
<p><img src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/figure-html/unnamed-chunk-6-1.png" width="960" /></p>
<p>Here is the equation below to find coefficient of skewness;</p>
<center>
<b>Coefficient of Skewness</b>
</center>
<p><span class="math display">\[C_{s}=\frac{n\sum_{i=1}^{n}(x_{i}-\bar{x})^3}{(n-1)(n-2)S^3} \]</span>
Dividing by <span class="math inline">\(S^3\)</span> makes this equation dimensionless. As you can see, it’s very similar to the variance.</p>
</div>
<div id="tailednesskurtosis" class="section level3">
<h3>Tailedness/Kurtosis</h3>
<p>Tailedness aka Kurtosis is the measure of the ‘<strong>tails</strong>’ of the distribution. This is really helpful with outliers in the distribution. Kurtosis gives you an idea of what’s going on at the edges. There are three flavors of kurtosis: mesokurtic, leptokurtic and platykurtic. These are based on different kurtosis values (k=3 is mesokurtic, k &gt; 3 is leptokurtic, k &lt; 3 is platykurtic). When you start playing around with kurtosis you’ll see that it really depends on <strong>how heavy</strong> areas of the distribution are! See the figure below and notice how the distributions look,</p>
<p><img src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/figure-html/unnamed-chunk-7-1.png" width="960" /></p>
<p>What you can’t see is how heavy the tails are! I had to add more points to the platykurtic distribution near the edges to get a k &lt; 0. Equation for type 3 coefficient of kurtosis.</p>
<center>
<b>Coefficient of Kurtosis</b>
</center>
<p><span class="math display">\[k=\frac{n^2\sum_{i=1}^{n}(x_{i}-\bar{x})^4}{(n-1)(n-2)(n-3)S^4} \]</span></p>
</div>
<div id="banfield-stats" class="section level3">
<h3>Banfield Stats</h3>
<p>Now that we’ve covered descriptive statistics, we can move on and see what the Banfield site looks like.</p>
<table>
<caption>April Daily Snow Water Equivalent (SWE) at Banfield Mountain</caption>
<thead>
<tr class="header">
<th>Mean</th>
<th>Median</th>
<th>Mode</th>
<th>Variance</th>
<th>Standard Deviation</th>
<th>Skewness</th>
<th>Kurtosis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>18.09 in.</td>
<td>17.1 in.</td>
<td>16 in.</td>
<td>42.84</td>
<td>6.55 in.</td>
<td>0.5</td>
<td>2.97</td>
</tr>
</tbody>
</table>
<p>From the table above we can see that the mean, median and mode (central tendancy) are pretty close. The standard deviation is about 6.55 inches (dispersion) and the skewness (measure of symmetry) is positive (0.5) which means skewed to the right. The kurtosis is interesting as it’s close to 3, which indicates that its <em>tails</em> likely follow a normal distribution (<strong>mesokurtic</strong>).</p>
<p>These handful of stats (table above) are very informative and give us a quick exploratory look into what’s going on with this sample. This can help us understand what the underlying data looks like (without looking) and can give us insights relatively fast but what if we wanted to ask some questions like, ‘what is the probability of seeing a SWE measurement in April above 25 inches?’. This is where we’ll need to introduce the idea of probability distributions.</p>
</div>
</div>
<div id="probability-distributions-univariate" class="section level2">
<h2>Probability Distributions (univariate)</h2>
<p>For us hydrologists, a univariate probability distribution is composed of randomly sampled data (discrete or continuous) from hydrologic events (rainfall, runoff, snow water equivalent (SWE), days of drought, etc) that we can then infer <strong>probabilities</strong> from an theoretical or empirical distribution. The main take-away is if we know what the distribution of the data is (empirical) or what it likely follows (theoretical) then we can do some powerful things with probabilities.</p>
<p>Thus, a <strong>probability</strong> distribution is broken into two different flavors: probability mass function (pmf) and probability density function (pdf). A pmf is made up of randomly sampled discrete data (number of days, months, years, etc) and a pdf is made up of randomly sampled continuous data (rainfall depth, snow depth, runoff). That’s it! Below we’ll dive into the math behind a pmf and pdf and also introduce a Cumulative Distribution Function (CDF), which calculates/cumulates the probabilities.</p>
<div id="pmf" class="section level3">
<h3>pmf</h3>
<p>The pmf must satisfy,</p>
<p><span class="math display">\[(i)\ \ \ p_{x}(x_{i}) \geq 0 \ \ \ \forall \ x_{i} \in \theta\]</span>
<span class="math display">\[(ii)\ \ \ \sum_{all \ i}p_{x}(x_{i})=1\]</span></p>
<p>where <span class="math inline">\(p_{x}(x_{i})\)</span> must be greater than or equal to zero for all x in the set and the sum of <span class="math inline">\(p_{x}(x_{i})\)</span> must equal one for all x in the set. Basically, we can’t have a set of values that when you add up them up they don’t equal one. Which makes sense intuitively, we wouldn’t want our sample to only go to 0.75. We can look at this with our (<span class="math inline">\(banfield\)</span>) dataset but first we’ll need to transfer into a discrete value to use as a pmf example (since it’s continuous data right now…).</p>
<p>Let’s see what the number/count of consecutive days of SWE per year is (blah, confusing). In other words, number of days in a row that SWE has increased day-to-day. For example, if you take <code>"2020-04-01 UTC" "2020-04-02 UTC" "2020-04-03 UTC" "2020-04-04 UTC"</code> and have SWE values <code>1,1,3,2</code> then this would have one consecutive day with a positive increase at days <code>"2020-04-02 UTC" "2020-04-03 UTC"</code> where SWE goes from <code>1 to 3</code> (notice that we’re not counting decreasing days <code>3 to 2</code>). When doing this we can see that our data closely follows a Poisson Distribution (<span class="math inline">\(P(x) = \frac{{e^{-\lambda} \lambda^x }}{{x!}}\)</span>).</p>
<p><img src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/figure-html/unnamed-chunk-8-1.png" width="960" /></p>
<p>In the figure above there are a lot of zero’s! This is what we would expect for the end of the season around here (more losing water than gaining). The inset figure show’s how it roughly (really really close) follows a Poisson distribution. So what do we do with the pmf?</p>
<p>That’s easy (relative), we just substitute <span class="math inline">\(p_{x}(x_{i})\)</span> for whatever the new distribution is; in our case that’s a Poisson distribution (<span class="math inline">\(\frac{e^{-\lambda}\lambda^x }{x!}\)</span> where <span class="math inline">\(\lambda=0.2\)</span>). Replace. And voila <span class="math inline">\(\sum_{all \ i}\frac{e^{-\lambda}\lambda^x }{x!}\)</span> where <span class="math inline">\(\lambda=0.2\)</span>. From here, we just have to ask a question like ‘what is the probability that there will be 0 consecutive days in April?’. All we do is plug in 0 to the Poisson Distribution and magic happens (wait no, no magic <strong>just a function</strong> being calculated). So,
<span class="math display">\[P(X=0)=p_{x}(0) = \frac{e^{-0.2}0.2^0 }{0!} = 0.819\]</span>
We could do this for any of the days if we wanted to (see figure below). In the case of <span class="math inline">\(p_{x}(0)\)</span> the probability is equal to 81.9%. What this means is that on any given day we would have a 81.9% chance of not seeing a consecutive day of increased SWE at the <span class="math inline">\(banfield\)</span> site in April.</p>
<p><img src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/figure-html/unnamed-chunk-9-1.png" width="960" /></p>
<p>What about 10? Easy, just substitute x for 10</p>
<p><span class="math display">\[p_{x}(10) = \frac{e^{-0.2}0.2^{10}}{10!} = 2.31\mathrm{e}{-14}\]</span>
Wow, that’s really rare to get 10 consecutive days! But what if we want to know what the probability of getting 1 or more consecutive days is? Since there is only 30 days in April we’ll cut it off at 30 (-sidebar, technically we could just do <span class="math inline">\(P(X\geq 1)\)</span> but for example sake we’ll look at it as an interval). Thus, we would just take the interval <span class="math inline">\(P(1\leq X \leq 30)\)</span> to find <span class="math inline">\(\sum_{all \ i}p_{x}(x_{i})\)</span>. Using this equation below,</p>
<p><span class="math display">\[ P(1\leq X \leq 30)= \sum_{all \ i}\frac{e^{-\lambda}\lambda^x_{i} }{x_{i}!} \ \mbox{where} \ \lambda = 0.2 \ \ \ \forall \ x_{i} \in \{1,2,3,4,\dots,30\}\]</span></p>
<p>we can then sum up all the probabilities greater than and equal to one to find <span class="math inline">\(P(1\leq X \leq 30)\)</span>. We can do this real quick in R using the {purrr} package with the <code>map</code> function. The result is 0.181.</p>
<pre class="r"><code>seq(1,30,1) %&gt;% map(function(x)(exp(-0.2)*0.2^x)/factorial(x)) %&gt;% unlist() %&gt;% sum()</code></pre>
<p>Now if we add these together <span class="math inline">\(P(X=0) + P(1\leq X \leq 30)\)</span> we should get 1, right? (<strong>remember it must follow the pmf rules</strong>, see eq. (<span class="math inline">\(ii\)</span>)). And, drumroll… we do (0.8187308 + 0.1812692 = 1)! We just used some hydrodrologic data (SWE) to find the probability of <span class="math inline">\(P(1\leq X \leq 30)\)</span> and <span class="math inline">\(P(X=0)\)</span>, how cool is that? But what about that thing called the CDF? The methods above (finding probabilities at different values and summing) are technically a CDF!</p>
<center>
<b>pmf Cumulative Distribution Function (CDF)</b>
</center>
<p><span class="math display">\[F_{x}(x_{i})=P(X\leq x_{i})=\sum_{j=i}^{i}P(X=x_{j}) \ \ \ \ \ \forall x \in \{x_{1},x_{2},x_{3},\dots,x_{n}\}\]</span></p>
<p>However, the CDF does it a different way with intervals than the way we did it by using <span class="math inline">\(P(1\leq X \leq 30) = F_{x}(30) - F_{x}(1)\)</span>. This is very subtle (<span class="math inline">\(p_{x}(x_{i}) \ \mbox{vs.} \ F_{X}(x)\)</span>) but very important. To calculate the interval CDF we need to follow this formula below,</p>
<p><span class="math display">\[ \mbox{For} \ 0 &lt; k \leq x \leq k \\ F_{x}(x) = p_{x}(0) + p_{x}(1) + \dots + p_{x}(k) \\ P(X) =  F_{x}(x_{i}) - F_{x}(x_{i})\]</span></p>
<p>Now if we want to find the <span class="math inline">\(P(1\leq X \leq 30)\)</span> using CDF we can! Just input the values into the equation above and we’ll get the same result as if summing up the interval.</p>
<p><span class="math display">\[
 P(1 \leq x \leq 30) = F_{x}(30) - F_{x}(1) \\
 F_{x}(30)= p_{x}(0)+p_{x}(1) + \dots +p_{x}(30) = 1\\
 F_{x}(1)= p_{x}(0) = 0.819 \\
 P(1 \leq x \leq 30) = 1-0.819=0.181
\]</span></p>
<p>They match! Let’s move onto continuous data and explore a pdf!</p>
<div class="b--green ba bw2 ma2 pa4 shadow-1">
<p><strong>Make sure to pay attention to <span class="math inline">\(\leq\)</span> and <span class="math inline">\(\geq\)</span> and &lt; or &gt; when using CDF’s with pmf’s. It is fine to add <span class="math inline">\(\leq\)</span>, <span class="math inline">\(\geq\)</span>, &lt; or &gt; when using CDF’s but the signs matter for pmf’s! This is not the case with pdf’s as we’ll see in a little bit.</strong></p>
</div>
</div>
<div id="pdf" class="section level3">
<h3>pdf</h3>
<p>With pdf’s we can start working with contiuous data. This is nice since the <span class="math inline">\(banfield\)</span> data is continuous to start out. First we’ll go over the pdf just like pmf and then apply with a cdf. There is an important distinction between the two (pmf and pdf) in that a pdf is not a point probability and a pmf is. That is to say, if we were to take a point estimate with a pdf then that value is a probability <em>density</em> and not a probability <em>value</em>. Nevertheless.</p>
<p>The pdf must satisfy,</p>
<p><span class="math display">\[(i)\ \ \ f(x) \geq 0 \ \ \ \mbox{for all} \ x \]</span>
<span class="math display">\[(ii)\ \ \ \int_{-\infty}^{\infty}f(x)dx=1\]</span>
Going back to the distribution of SWE in April at <span class="math inline">\(banfield\)</span> we can see that the distribution closely follows a normal distribution (<strong>assuming</strong>, see below figure).</p>
<p><img src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/figure-html/unnamed-chunk-11-1.png" width="960" />
Just like the pmf we can take a probability <em>density</em> function <span class="math inline">\(f(x)\)</span> and use it to figure out probabilities for different ranges. In our case, <span class="math inline">\({\displaystyle f(x)={\frac {1}{\sqrt {2\pi \sigma^2 }}}\;e^{-(x-\mu)^{2}/2\sigma^2}}\)</span>, (aka the pdf of the normal distribution) and it can be used to answer questions like ‘what is the probability that we have a SWE value <span class="math inline">\(\geq\)</span> 20?’. Instead of summing up the point probabilities like a pmf we’ll integrate from 20 to <span class="math inline">\(\infty\)</span>. Just like the CDF for a pmf but now we will use integration to find the probability.</p>
<center>
<b>pdf Cumulative Distribution Function (CDF)</b>
</center>
<p><span class="math display">\[
{\displaystyle F_{x}(x)=P(X\geq 20)=\int_{20}^{\infty}{\frac {1}{\sqrt {2\pi \sigma^2 }}}\;e^{-(x-\mu)^{2}/2\sigma^2}} = \ ?
\]</span>
To do this in R we’ll need to use the <code>integrate()</code> but first we’ll need to find the Z value at 20. The Z-value is equal to <span class="math inline">\(Z=\frac{(value - \overline{x})}{s^2}\)</span>, so mean = 18.09 and standard deviation = 6.55 then <span class="math inline">\(Z=\frac{(20-18.09)}{6.545}=0.29\)</span>. Now we can calculate the <span class="math inline">\(P(X\geq 20)\)</span>. Below we’ll show using the <code>dnorm()</code> function which is the <em>standard normal</em> distribution (<span class="math inline">\(f(x)=f{\frac {1}{\sqrt {2\pi }}}\;e^{-x^{2}/2}\)</span>) and then manually showing the normal distribution pdf with our data stats (mean and sd). They are a little different but not by much… This has to do with the mean and standard deviation of the two and as a side note this is why it is important to match the <strong>best</strong> fitting distribution!</p>
<pre class="r"><code>integrate(dnorm, 0.29, Inf)</code></pre>
<pre><code>## 0.3859081 with absolute error &lt; 7.5e-06</code></pre>
<pre class="r"><code>integrate(function(x)1/(6.545*sqrt(2*pi))*exp(-((x-18.09)^2/(2*6.545^2))), 20, Inf)</code></pre>
<pre><code>## 0.3852099 with absolute error &lt; 6.4e-08</code></pre>
<pre class="r"><code># or use
##  dnorm(.29)

### or take the area of each sliver of density*width and sum,
### you&#39;ll notice it&#39;s different and that&#39;s because we are using
### the mean = 18.09 and sd = 6.545. 
### Another topic, but they&#39;re different. Think about it....

### sum(dnorm(seq(20,30,0.00001), mean = 18.09, sd = 6.545)*0.00001)</code></pre>
<p>We ended up getting a probability of 0.386 or 38.6%. This makes sense though if we look at the curve and eyeball as seen in the graph below.</p>
<p><img src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/figure-html/unnamed-chunk-13-1.png" width="960" /></p>
<p>If we want to find it using a interval CDF we still use the same equation as the pmf, e.g. <span class="math inline">\(P(20&lt; X &lt; 25) = F_{X}(25) - F_{X}(20)\)</span>. Now we need to integrate from 0 to 20 and 0 to 25.</p>
<div class="b--red ba bw2 ma2 pa4 shadow-1">
<p><strong>Important note! Make sure to pay attention to <span class="math inline">\(\leq\)</span> and <span class="math inline">\(\geq\)</span> when using CDF’s with pdf’s. It is fine to add <span class="math inline">\(\leq\)</span> and <span class="math inline">\(\geq\)</span> instead of &lt; or &gt; for pdf’s but technically it’s not a point probability, e.g. <span class="math inline">\(P(X=d)=\int_{d}^{d}f(x)dx=0\)</span>! In other words, don’t assume <span class="math inline">\(P(X = 20)\)</span> to give you a point probability when working with pdf’s (only special cases like zero-inflated daily rainfall, etc)…</strong></p>
</div>
<p><span class="math display">\[
{\displaystyle P(20&lt; X &lt; 25)=\int_{0}^{25}{\frac {1}{\sqrt {2\pi \sigma^2 }}}\;e^{-(x-\mu)^{2}/2\sigma^2}-\int_{0}^{20}{\frac {1}{\sqrt {2\pi \sigma^2 }}}\;e^{-(x-\mu)^{2}/2\sigma^2}} \\ 
{\displaystyle \int_{0}^{25}{\frac {1}{\sqrt {2\pi \sigma^2 }}}\;e^{-(x-\mu)^{2}/2\sigma^2}} = 0.854  \\
{\displaystyle \int_{0}^{20}{\frac {1}{\sqrt {2\pi \sigma^2 }}}\;e^{-(x-\mu)^{2}/2\sigma^2}} = 0.614 \\
P(20&lt; X &lt; 25)=0.854-0.614=0.24
\]</span><br />
We can see the chunk of the normal distribution that we took out. We take the 20 and 25 and convert to Z values and then integrate using the normal distribution. This is why it is nice to fit to a theoretical distribution, i.e. don’t have to reinvent the wheel. The result is the area under the curve and the associated CDF aka probability of 20 to 25 inches of SWE in April!<br />
<img src="https://hydroblog.netlify.com/blog/2021-06-07-hydroclimatic-distributions/2021-06-07-hydroclimatic-distributions/hydro_dist_1/index_files/figure-html/unnamed-chunk-14-1.png" width="960" /></p>
<p>Hopefully this will help you understand hydrologic data better in the context of pmf, pdf and CDF. This will also help for upcoming flood frequency and goodness of fit blogs in the future. Thanks and hope you enjoyed!</p>
</div>
</div>
</div>
<div id="references" class="section level1">
<h1>References</h1>
</div>

      </section>
      <footer class="post-footer">
        <div class="post-pagination dt w-100 mt4 mb2">
  
  
  
  
</div>

      </footer>
    </article>
    
      
<div class="post-comments pa0 pa4-l mt4">

</div>


    
  </section>
</main>
<aside class="page-sidebar" role="complementary">
                         
 


                       
 











  <img src="/blog/2021-06-07-hydroclimatic-distributions/sidebar-listing.png" class="db ma0">


<div class="blog-info ph4 pt4 pb4 pb0-l">
  

  <h1 class="f3">What are descriptive statistics?</h1>
  <p class="f6 lh-copy measure">Descriptive statistics are expressions of summary statistics (mean, standard deviation, skewness, kurtosis, etc) from a sample of data. These are crucial for exploratory data analysis (EDA) and help the user frame the sample relatively quickly. Like in the graph above we can see that the data is normally distributed but the kurtosis is different.</p>
  <p class="f7 measure lh-copy i mh0-l">Written by Josh Erickson</p>


  
</div>


<div class="ad-unit pa4">
  
  <p class="f7 measure-narrow lh-copy mv0 pt5"><span class="b ttu db">Made by Formspree</span><span><a href="https://formspree.io" target="_blank">Formspree is a form backend, API and email  service for HTML forms</a>. It is the simplest way to collect form submissions on your static website.</span></p>
  
</div>

  
  <details open class="f6 fw7 input-reset">
  <dl class="f6 lh-copy">
    <dt class="fw7">Posted on:</dt>
    <dd class="fw5 ml0">June 7, 2021</dd>
  </dl>
  <dl class="f6 lh-copy">
    <dt class="fw7">Length:</dt>
    <dd class="fw5 ml0">14 minute read, 2961 words</dd>
  </dl>
  
  <dl class="f6 lh-copy">
    <dt class="fw7">Categories:</dt>
    <dd class="fw5 ml0"> <a href="https://hydroblog.netlify.com/categories/r">R</a>  <a href="https://hydroblog.netlify.com/categories/hydrology">Hydrology</a> </dd>
  </dl>
  
  
  
  <dl class="f6 lh-copy">
    <dt class="fw7">Tags:</dt>
    <dd class="fw5 ml0"> <a href="https://hydroblog.netlify.com/tags/r">R</a>  <a href="https://hydroblog.netlify.com/tags/hydrology">Hydrology</a> </dd>
  </dl>
  
  <dl class="f6 lh-copy">
    <dt class="fw7">See Also:</dt>
    
    <dd class="fw5 ml0"><a href="/project/wildlandhydro/">wildlandhydRo is a package that leverages USGS and SNOTEL APIs.</a></dd>
    
    <dd class="fw5 ml0"><a href="/project/explorergee/">exploreRGEE</a></dd>
    
    <dd class="fw5 ml0"><a href="/blog/anova/">ANOVA</a></dd>
    
  </dl>
</details>

</aside>
<footer class="site-footer pv4 bt b--transparent ph5" role="contentinfo">
  <nav class="db dt-l w-100">
    <p class="site-copyright f7 db dtc-l v-mid w-100 w-33-l tc tl-l pv2 pv0-l mv0 lh-copy">
      &copy; 2021 RStudio, Anywhere
      <span class="middot-divider"></span>
      Made with <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title"><a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/hugo-apero/" rel="dct:source">Hugo Apéro</a></span>.
      <br />
      
Based on <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title"><a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/formspree/blogophonic-hugo" rel="dct:source">Blogophonic</a></span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://formspree.io" property="cc:attributionName" rel="cc:attributionURL">Formspree</a>.
    </p>
    
    <div class="site-social-links db dtc-l v-mid w-100 w-33-l tc pv2 pv0-l mv0">
      <div class="social-icon-links" aria-hidden="true">
  
  
    
    
    
      
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://github.com/joshualerickson" title="github" target="_blank" rel="noopener">
      <i class="fab fa-github fa-lg fa-fw"></i>
    </a>
  
    
    
    
      
    
    
    
    
    
      
    
    <a class="link dib h1 w1 ml0 mr2 f6 o-90 glow" href="https://twitter.com/joshualerickson" title="twitter" target="_blank" rel="noopener">
      <i class="fab fa-twitter fa-lg fa-fw"></i>
    </a>
  
</div>

    </div>
    
    <div class="site-links f6 db dtc-l v-mid w-100 w-67-l tc tr-l pv2 pv0-l mv0">
      
    </div>
  </nav>
  <script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
</footer>

      </div>
    </body>
</html>
