---
title: Hydrology Distributions
author: Josh Erickson
date: '2021-06-07'
slug: []
categories: []
tags: []
description: 'Demystifying? Wait, what?'
---


```{r, message=FALSE, warning=FALSE}
library(wildlandhydRo)
library(evd)
library(fitdistrplus)
library(tidyverse)
```

# Introduction
This will be part one of a three part blog post where we'll look at different distributions in R using the {wildlandhydRo} and {tidyverse} packages. A lot of times in hydrology you'll end up collecting data (rainfall, snowdepth, runoff, etc) to try and fit to an theoretical distribution (univariate Cumulative Distribution Functions (CDF)) to then use for further analysis, e.g. frequency, probabilities, etc. These CDF's come in all shapes and sizes (literally) and can be confusing at times but hopefully we can demystify them in this blog series without too much incredulity from those pesky statisticians. First, we'll look at what a CDF is for some commonly used empirical distributions in hydrology, e.g. normal (N), lognormal (LN), log Pearson type III (LP3), Pearson (P), Gumbel (G), Weibull (W) and Generalized Extreme-value Distribution (GEV). Second, we'll bring in some data and look at the distributions visually. Third, we'll use a few goodness-of-fit tests to see which theoretical distribution best represents the underlying empirical distribution.

## Part I

For part one we will get pretty '_mathy_' with the distributions by looking at the derivations of the CDF's. This will involve some calculus but is mostly just looking at where and why $$f(x)$$ goes where it goes. 

 $$
 \begin{aligned}
 &E[X] = \int_{-\infty}^{\infty} xf(x) dx=\\ 
 &\int_{0}^{1} x dx    = \frac12 x^2 |_0^1 = \frac12 
 \end{aligned}
 $$

$f(x_{i},y_{i})$



