---
title: 'Hydrology Distributions: Part II'
author: Josh Erickson
date: '2021-06-07'
slug: []
categories: []
tags: []
description: 'Demystifying? Wait, what?'
output:
  blogdown::html_page:
    toc: true

always_allow_html: true
---


```{r, message=FALSE, warning=FALSE}
library(wildlandhydRo)
library(evd)
library(fitdistrplus)
library(tidyverse)
library(patchwork)
library(latex2exp)
library(moments)
theme_set(theme_bw())
```

# Introduction

This will be part two of a three part blog series *'Hydrology Distributions'* where we'll look at different distributions in R using a handful of packages. A lot of times in hydrology you'll end up collecting data (rainfall, snowdepth, runoff, etc) to try and fit a theoretical distribution for further analysis, e.g. frequency, probabilities, hypothesis testing etc. These probability distributions come in all shapes and sizes (literally) and can be confusing at times but hopefully we can break these concepts down without too much incredulity from those pesky/pedantic statisticians `r emo::ji('blush')`. First ([part I](https://hydroblog.netlify.app/2021/06/07/2021-06-07-hydroclimatic-distributions/)), we'll look at descriptive statistics and probability distributions (pmf and pdf). Second (part II), we'll bring in some data and compare distributions visually for some commonly used theoretical distributions in hydrology, e.g. normal (N), Lognormal (LN), Log-Pearson Type III (LP3), Pearson Type III (P3), Gumbel (G), Weibull (W) and Generalized Extreme-value Distribution (GEV). Third (part III), we'll use a few goodness-of-fit tests to see which theoretical distribution best represents the underlying empirical distribution.

# Part II

In ([part I](https://hydroblog.netlify.app/2021/06/07/2021-06-07-hydroclimatic-distributions/)) we went over probability mass functions (pmf) and probability density functions (pdf) as well as introduce the cumulative distribution functions (cdf). If you haven't read part I please go back and read unless you are comfortable with these aforementioned topics. In part II we will go beyond the normal distribution and start looking at other distributions that are commonly used in hydrology. We will focus on reoccurence intervals, which will only involve continuous distributions so discrete will have to be for another time `r emo::ji('sad')`. In part one we talked about pdf's and how we can use theoretical pdf's as a proxy for our sampled data. We just looked at the normal distribution in part one but there are many other relavant pdf's in hydroclimatic variables. We can use these theoretical pdf's to our advantage since they have already been worked out mathematically! From there, we can introduce the idea of a reoccurence interval and how one would go about calculating it but first we'll go through the pdf's mathematically and visually.  

# Theoretical PDF's  

I know it's a lot but I think it's helpful to just see the different pdf's ($f_{x}(x)$) written out symbolically. Thus, we'll look at the following distributions: normal (N), Lognormal (LN), Log-Pearson Type III (LP3), Pearson Type III (P), Gumbel (G), Weibull (W) and Generalized Extreme-value Distribution (GEV).  

:::: {style="display: flex;"}

::: {style="flex-basis: 10px;"}
<center>
**Normal**
</center>
$$
{\scriptsize\displaystyle {\frac {1}{\sqrt {2\pi \sigma^2 }}}\;e^{-(x-\mu)^{2}/2\sigma^2}}
$$
:::

::: {style="flex-basis: 50px;"}

:::

::: {style="flex-basis: 10px;"}
<center>
**Lognormal**
</center>
$$
{\scriptsize\displaystyle {\frac {1}{\sqrt {2\pi \beta^2 }}}\;e^{-\ln(x-\alpha)^{2}/2\beta^2}}
$$
:::

::: {style="flex-basis: 50px;"}

:::
::: {style="flex-basis: 10px;"}
<center>
**Log-Pearson III**
</center>
$$ 
{\scriptsize\displaystyle {\frac {\lambda^\beta(\log(x)-\epsilon)^{\beta-1}e^{-\lambda(\log(x)-\epsilon)}}{\Gamma(\beta)}}}
$$
:::

::: {style="flex-basis: 50px;"}

:::
::: {style="flex-basis: 1%;"}
<center>
**Pearson III**
</center>
$$
{\scriptsize\displaystyle {\frac {\lambda^\beta(x-\epsilon)^{\beta-1}e^{-\lambda(x-\epsilon)}}{\Gamma(\beta)}}}
$$
:::
::::  

<br>  

:::: {style="display: flex;"}
::: {style="flex-basis: 150px;"}

:::
::: {style="flex-basis: 10px;"}
<center>
**Gumbel**
</center>
$$
{\scriptsize\displaystyle {\frac {\lambda^\beta(x-\epsilon)^{\beta-1}e^{-\lambda(x-\epsilon)}}{\Gamma(\beta)}}}
$$
:::

::: {style="flex-basis: 50px;"}

:::
::: {style="flex-basis: 1%;"}
<center>
**Weibull**
</center>
$$
{\scriptsize\displaystyle {\frac {\lambda^\beta(x-\epsilon)^{\beta-1}e^{-\lambda(x-\epsilon)}}{\Gamma(\beta)}}}
$$
:::

::: {style="flex-basis: 50px;"}

:::
::: {style="flex-basis: 1%;"}
<center>
**GEV**
</center>
$$
{\scriptsize\displaystyle {\frac {\lambda^\beta(x-\epsilon)^{\beta-1}e^{-\lambda(x-\epsilon)}}{\Gamma(\beta)}}}
$$
:::
::: {style="flex-basis: 150px;"}

:::
::::